In [52]:
import pandas as pd 
import numpy as np

In [53]:
df = pd.read_csv("C:/Users/user/Downloads/spam.csv")
df

Category                                            Message
0         ham  Go until jurong point, crazy.. Available only ...
1         ham                      Ok lar... Joking wif u oni...
2        spam  Free entry in 2 a wkly comp to win FA Cup fina...
3         ham  U dun say so early hor... U c already then say...
4         ham  Nah I don't think he goes to usf, he lives aro...
...       ...                                                ...
5567     spam  This is the 2nd time we have tried 2 contact u...
5568      ham               Will ü b going to esplanade fr home?
5569      ham  Pity, * was in mood for that. So...any other s...
5570      ham  The guy did some bitching but I acted like i'd...
5571      ham                         Rofl. Its true to its name

[5572 rows x 2 columns]

In [54]:
df.Category.value_counts()

Category
ham     4825
spam     747
Name: count, dtype: int64

In [55]:
df['spam'] = df['Category'].apply(lambda x: 1 if x == 'spam' else 0)

In [56]:
df.head()

Category                                            Message  spam
0      ham  Go until jurong point, crazy.. Available only ...     0
1      ham                      Ok lar... Joking wif u oni...     0
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...     1
3      ham  U dun say so early hor... U c already then say...     0
4      ham  Nah I don't think he goes to usf, he lives aro...     0

In [57]:
from sklearn.model_selection import train_test_split 

In [58]:
X_train, X_test, y_train, y_test = train_test_split(df.Message, df.spam, test_size=0.2)

In [59]:
X_train.shape

(4457,)

In [60]:
X_test.shape

(1115,)

In [61]:
type(X_train)

pandas.core.series.Series

In [62]:
X_train[:5]

2768               Wow v v impressed. Have funs shopping!
5407    Yup he msg me: is tat yijue? Then i tot it's m...
3879         What you need. You have a person to give na.
918     When people see my msgs, They think Iam addict...
3235                                  Yup ü not comin :-(
Name: Message, dtype: object

In [63]:
type(y_train)

pandas.core.series.Series

In [64]:
y_train[:4]

2768    0
5407    0
3879    0
918     0
Name: spam, dtype: int64

In [65]:
type(X_train.values )

numpy.ndarray

In [66]:
from sklearn.feature_extraction.text import CountVectorizer 

v = CountVectorizer()

X_train_cv = v.fit_transform(X_train.values)
X_train_cv

<4457x7768 sparse matrix of type '<class 'numpy.int64'>'
	with 59124 stored elements in Compressed Sparse Row format>

In [67]:
X_train_cv.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [68]:
X_train_cv.toarray()[:2][0]

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [69]:
X_train_cv.shape

(4457, 7768)

In [70]:
v.get_feature_names_out()[:20]

array(['00', '000', '000pes', '008704050406', '0089', '01223585236',
       '01223585334', '0125698789', '02', '0207', '02072069400',
       '02073162414', '02085076972', '021', '03', '04', '05', '0578',
       '06', '07'], dtype=object)

In [71]:
v.get_feature_names_out()[1000:1020]

array(['apology', 'app', 'apparently', 'appeal', 'appear', 'appendix',
       'applausestore', 'applebees', 'application', 'apply', 'applying',
       'appointment', 'appointments', 'appreciate', 'appreciated',
       'approaches', 'appropriate', 'approve', 'approved', 'approx'],
      dtype=object)

In [72]:
v.get_feature_names_out().shape

(7768,)

In [73]:
dir(v)

['__annotations__',
 '__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__setstate__',
 '__sizeof__',
 '__sklearn_clone__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_build_request_for_signature',
 '_char_ngrams',
 '_char_wb_ngrams',
 '_check_feature_names',
 '_check_n_features',
 '_check_stop_words_consistency',
 '_check_vocabulary',
 '_count_vocab',
 '_get_default_requests',
 '_get_metadata_request',
 '_get_param_names',
 '_get_tags',
 '_limit_features',
 '_more_tags',
 '_parameter_constraints',
 '_repr_html_',
 '_repr_html_inner',
 '_repr_mimebundle_',
 '_sort_features',
 '_stop_words_id',
 '_validate_data',
 '_validate_ngram_range',
 '_validate_params',
 '_validate_vocabulary',
 '_warn_for_unused_params',

In [74]:
v.vocabulary_

{'wow': 7640,
 'impressed': 3657,
 'have': 3384,
 'funs': 3070,
 'shopping': 6148,
 'yup': 7751,
 'he': 3395,
 'msg': 4632,
 'me': 4425,
 'is': 3770,
 'tat': 6748,
 'yijue': 7723,
 'then': 6855,
 'tot': 7022,
 'it': 3781,
 'my': 4680,
 'group': 3281,
 'mate': 4398,
 'cos': 2027,
 'we': 7446,
 'meeting': 4444,
 'today': 6969,
 'mah': 4334,
 'askin': 1080,
 'if': 3624,
 'leaving': 4088,
 'earlier': 2521,
 'or': 4996,
 'wat': 7429,
 'mayb': 4418,
 'haf': 3321,
 'to': 6963,
 'walk': 7395,
 'far': 2800,
 'what': 7502,
 'you': 7730,
 'need': 4743,
 'person': 5191,
 'give': 3168,
 'na': 4690,
 'when': 7508,
 'people': 5173,
 'see': 6023,
 'msgs': 4637,
 'they': 6867,
 'think': 6873,
 'iam': 3597,
 'addicted': 788,
 'msging': 4634,
 'are': 1032,
 'wrong': 7650,
 'bcoz': 1257,
 'don': 2420,
 'know': 3986,
 'that': 6842,
 'sweet': 6690,
 'friends': 3026,
 'bslvyl': 1529,
 'not': 4850,
 'comin': 1912,
 'got': 3229,
 'lousy': 4244,
 'sleep': 6255,
 'kept': 3937,
 'waking': 7393,
 'up': 7212,
 'eve

In [76]:
v.get_feature_names_out()[7640]

'wow'

In [78]:
X_train_np = X_train_cv.toarray()

X_train_np[0]

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [81]:
np.where(X_train_np[0]!=0)

(array([3070, 3384, 3657, 6148, 7640], dtype=int64),)

In [89]:
X_train[:4]

2768               Wow v v impressed. Have funs shopping!
5407    Yup he msg me: is tat yijue? Then i tot it's m...
3879         What you need. You have a person to give na.
918     When people see my msgs, They think Iam addict...
Name: Message, dtype: object

In [86]:
X_train_np[0][1771]

0

In [91]:
X_train_np[0][3070]

1

In [93]:
from sklearn.naive_bayes import MultinomialNB 

model = MultinomialNB()

model.fit(X_train_cv, y_train)

MultinomialNB()

In [94]:
X_test_cv = v.transform(X_test)

In [95]:
from sklearn.metrics import classification_report

y_pred = model.predict(X_test_cv)

print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.99      1.00      0.99       959
           1       0.98      0.93      0.95       156

    accuracy                           0.99      1115
   macro avg       0.98      0.96      0.97      1115
weighted avg       0.99      0.99      0.99      1115



In [96]:
emails = [
    'Hey mohan, can we get together to watch footbal game tomorrow?',
    'Upto 20% discount on parking, exclusive offer just for you. Dont miss this reward!'
]

emails_count = v.transform(emails)
model.predict(emails_count)

array([0, 1], dtype=int64)

In [97]:
from sklearn.pipeline import Pipeline

clf = Pipeline([
    ('vectorizer', CountVectorizer()),
    ('nb', MultinomialNB())
])

In [98]:
clf.fit(X_train, y_train)

Pipeline(steps=[('vectorizer', CountVectorizer()), ('nb', MultinomialNB())])

In [99]:
y_pred = clf.predict(X_test)

print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.99      1.00      0.99       959
           1       0.98      0.93      0.95       156

    accuracy                           0.99      1115
   macro avg       0.98      0.96      0.97      1115
weighted avg       0.99      0.99      0.99      1115

